from typing import AnyStr


def WebPEncode(a: bytes, b: int, c: int, d: int, e: float, f: str, g: AnyStr, h: AnyStr, i: AnyStr) -> None: ...

def WebPDecode(a: bytes) -> None: ...

def WebPDecoderVersion() -> int: ...

def WebPDecoderBuggyAlpha() -> int: ...